export const bank = [
  { code: "Escape", id: "clear" },
  { code: "Backspace", id: "erase" },
  { code: "Enter", id: "equals" },
  { code: "NumpadSubtract", id: "subtract" },
  { code: "NumpadAdd", id: "add" },
  { code: "NumpadMultiply", id: "multiply" },
  { code: "Digit5", id: "mod" },
  { code: "Slash", id: "divide" },
  { code: "Numpad0", id: "zero" },
  { code: "Numpad1", id: "one" },
  { code: "Numpad2", id: "two" },
  { code: "Numpad3", id: "three" },
  { code: "Numpad4", id: "four" },
  { code: "Numpad5", id: "five" },
  { code: "Numpad6", id: "six" },
  { code: "Numpad7", id: "seven" },
  { code: "Numpad8", id: "eight" },
  { code: "Numpad9", id: "nine" },
  { code: "NumpadDecimal", id: "decimal" },
];
